//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WzComparerR2.MapRender.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WzComparerR2.MapRender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_normal_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_normal_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_normal_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_normal_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ComboBox_normal_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ComboBox_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ComboBox_normal_1 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ComboBox_normal_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ComboBox_normal_2 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ComboBox_normal_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_box {
            get {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_c {
            get {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_c_box {
            get {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_c_box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_s {
            get {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_s_box {
            get {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_s_box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_t {
            get {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_0 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_1 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_2 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_3 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_4 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_5 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_6 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_7 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_8 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_9 {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_left {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_Bracket_right {
            get {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_Bracket_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_input_layer_backgrnd {
            get {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_input_layer_backgrnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_input_layer_chatEnter {
            get {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_input_layer_chatEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_view_max_bottom {
            get {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_view_max_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_view_max_center {
            get {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_view_max_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_view_max_top {
            get {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_view_max_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtFilter_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtFilter_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtFilter_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtFilter_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtFilter_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtFilter_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtFilter_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtFilter_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtMap_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtMap_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtMap_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtMap_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtMap_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtMap_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtMap_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtMap_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNavigation_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNavigation_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNavigation_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNavigation_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNavigation_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNavigation_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNavigation_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNavigation_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNpc_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNpc_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNpc_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNpc_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNpc_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNpc_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtNpc_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtNpc_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtTown_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtTown_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtTown_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtTown_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtTown_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtTown_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_BtTown_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_BtTown_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_c {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_e {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_n {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_ne {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_ne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_nw {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_nw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_s {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_se {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_se", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_sw {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_sw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_sw2 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_sw2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_MaxMap_w {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_MaxMap_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_Min_c {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_Min_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_Min_e {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_Min_e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_MiniMap_Min_w {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_MiniMap_Min_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_backgrnd {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_backgrnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_close_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_close_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_close_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_close_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_close_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_close_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_close_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_close_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToCurrentMap_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToCurrentMap_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToCurrentMap_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToCurrentMap_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToCurrentMap_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToCurrentMap_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToCurrentMap_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToCurrentMap_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToUpperWorldMap_disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToUpperWorldMap_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToUpperWorldMap_mouseOver_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToUpperWorldMap_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToUpperWorldMap_normal_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToUpperWorldMap_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_button_goToUpperWorldMap_pressed_0 {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_button_goToUpperWorldMap_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UI_UIMap_img_WorldMap_mapInfo_layer_mapInfoCover {
            get {
                object obj = ResourceManager.GetObject("UI_UIMap_img_WorldMap_mapInfo_layer_mapInfoCover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_ArcaneForce {
            get {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_ArcaneForce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_AuthenticForce {
            get {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_AuthenticForce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_enchantMob {
            get {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_enchantMob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_Line {
            get {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_Mob {
            get {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_Mob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_Npc {
            get {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_Npc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_StarForce {
            get {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_StarForce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow2_img_Teleport_customBG {
            get {
                object obj = ResourceManager.GetObject("UIWindow2_img_Teleport_customBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow2_img_WorldMap_Border_0 {
            get {
                object obj = ResourceManager.GetObject("UIWindow2_img_WorldMap_Border_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow3_img_mirrorFrame_1024 {
            get {
                object obj = ResourceManager.GetObject("UIWindow3_img_mirrorFrame_1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow3_img_mirrorFrame_1366 {
            get {
                object obj = ResourceManager.GetObject("UIWindow3_img_mirrorFrame_1366", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow3_img_mirrorFrame_800 {
            get {
                object obj = ResourceManager.GetObject("UIWindow3_img_mirrorFrame_800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
